#!/bin/bash

# If docker-compose is already installed, just run the containers. Else install dependencies first
if [ -e /usr/local/bin/docker-compose ]
then
  # Run the containers
  export APP_ENV=production
  docker-compose up --build
else
  # Install docker-ce
  sudo apt-get update
  sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
  sudo apt-get update
  sudo apt-get install -y docker-ce

  # Install docker-compose
  sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose

  # Install node
  sudo apt-get install -y nodejs npm

  cd api/
  npm install
  cd ..
  cd frontend
  npm install

  # Add user to docker group
  sudo usermod -aG docker $USER
  sudo su - $USER

  echo "Dependencies installed. Run:\n"
  echo "cd aquablogPosts && ./deploy"
fi
